---
name: 'Tests: E2E linters'

'on': [push]

jobs:
    tests_e2e:
        name: Run linters
        runs-on: ubuntu-latest
        steps:
            - uses: git push --set-upstream origin update-readme
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Typecheck
              run: npm run tsc
            - name: Detect unused code
              run: npm run knip
            - name: Build API documentation
              run: npm run typedoc
