name: Playwright Tests
on:
    push:
        branches: [main, master]
jobs:
    run_e2e:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                shard: [1, 2]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Install Playwright dependencies
              run: npx playwright install
            - name: Lint
              run: npm run lint
            - name: Typecheck
              run: npm run tsc
            - name: Load env
              run: |
                  cp .env.example .env
                  cat .env >> $GITHUB_ENV
            - name: Run tests
              run: npm run test -- --retries=1 --shard ${{ matrix.shard }}/2
              shell: bash
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report-${{ matrix.shard }}
                  path: ./playwright-report/
                  retention-days: 30
